spring:
  mail:
    host: smtp.example.com
    port: 587
    username: sriramvanguri7@gmail.com
    password: 12345678
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
